[package]
name = "unifier_set"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpds = "0.12.0"

[dev-dependencies]
dot_graph = "0.2.3"
